### ISSUE TITLE
./soggy: error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xi-forgetme** [LDAsuku/soggy#1]
Ubuntu 22.04.5 LTS

**Comment by LDAsuku** [comment]
try `apt install libprotobuf23`?

**Comment by YYLMZXC** [comment]
I have the same problem
Ubuntu 20.04.2 LTS

**Comment by xi-forgetme** [comment]
I have solved this by compiling protobuf by myself, however, i got another problem with GLIBCXX-2.34 smth

**Comment by xi-forgetme** [comment]
Could you please tell me which version of Ubuntu or Arch do you use?

**Comment by xi-forgetme** [comment]
Ok, this problem is solved. Just compile by yourself.
