### ISSUE TITLE
编译后无法正确运行伺服器

### ISSUE THREAD

**Issue by xiaomoL444** [LDAsuku/soggy#11]
![image](https://user-images.githubusercontent.com/69074564/209297467-5e2a524a-0ae4-49f5-ae79-584502e4b4b6.png)
一运行后就会报错，抱歉我不知道是哪里出了问题

**Comment by wiors** [comment]
Try to build using MSYS2/mingw64

**Comment by xiaomoL444** [comment]
It solved,thanks!

> Try to build using MSYS2/mingw64
