### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by njdawlk0293** [LDAsuku/soggy#5]
Hi, I get these errors while gs loading, how to fix it?
![3](https://user-images.githubusercontent.com/88573435/205106206-893ea838-65d0-4563-b21a-05c6f00699ff.png)
![2](https://user-images.githubusercontent.com/88573435/205106198-5e1a1bc9-d310-4b12-afa2-eb0b2db2d4cb.png)

**Comment by DenSwitch** [comment]
same problem

**Comment by LDAsuku** [comment]
I believe this is a bug with the game. others with the same issue have had success by changing their system language to english.

**Comment by DenSwitch** [comment]
> I believe this is a bug with the game. others with the same issue have had success by changing their system language to english.

yup. I've tried on fresh english win10 and the game works just fine :)

**Comment by njdawlk0293** [comment]
> I believe this is a bug with the game. others with the same issue have had success by changing their system language to english.

nice, it works for me too
