### ISSUE TITLE
Resources missing, need some help

### ISSUE THREAD

**Issue by M4tEd** [LDAsuku/soggy#6]
Hey, I'm not too familiar with github or which files to edit but I came across this error when running CMakeLists.txt
![image](https://user-images.githubusercontent.com/119826524/205549878-f067d646-eed2-4caf-8616-25cd0ae4acd0.png)
I tried to see every folder related to resources on my computer, I found a couple but none of them matched stuff like exceloutput or the .tsv files.

I don't know if I was supposed to run this file or not but the instructions are too difficult for my tiny brain. Could you help me with some directions?

I would also appreciate if you could tell me how to do the client patches. I don't seem to have a proper editor to edit a .dll or the GS.exe

**Comment by LDAsuku** [comment]
Resources link has been added to the wiki.

As for the client patches, a hex editor is required. (I recommend HxD)

**Comment by M4tEd** [comment]
Thanks for the help, I was able to find resources and HxD was useful for editing GS.exe and UserAssembly. I managed to launch the server but one question I have is how do you make GS use the emulated server? When I launch it I always get the network exception.

**Comment by LDAsuku** [comment]
You need a proxy, same method as Grasscutter; Fiddler or mitmproxy are the most popular on Windows. You can try [saturnine](https://github.com/timing1337/saturnine)'s Fiddler script or Grasscutter's mitmproxy script. I'm told Cultivation works, too.

**Comment by M4tEd** [comment]
I joined Grasscutter discord earlier and had some help. In your read me you should probably mention to run dispatch.py. If they didn't tell me about this file I would've never figured this out.

**Comment by LDAsuku** [comment]
Alright, thanks for the tip. I'll add that in my next commit.
