### ISSUE TITLE
Two questions about the guide?

### ISSUE THREAD

**Issue by Bvnniez** [LDAsuku/soggy#7]
Hi! So I decided to try this private server for the CBT1 since I was really curious about it, I was following the steps that come, but I ran into two problems, first uh do you need an specific client? (this is, since it mentions ''open your CBT1 client'' so I'm trying to make sure I don't need one in specific since I just have the normal Genshin) and second, I'm not sure if I'm following correctly the guide, but when I try to type the number of the proxy server in proxy.bat it doesn't allow me to type and after a few seconds it ''connects'' to a proxy? I don't really understand a lot this type of things so I'm sorry if this sounds stupid or annoying. # #

**Comment by LDAsuku** [comment]
The guide you're following wasn't written by me. Ask the uploader of the guide for help. This repo is only for the server emulator software, it doesn't serve as a guide.

**Comment by Bvnniez** [comment]
Oh thank you for your reply! I was following this one https://github.com/360NENZ/LDAsuku-soggy/releases/tag/CBT1 that I saw on the releases page iirc? I'm kinda new to github so i'm still learning how to use it, sorry if the question was a little unnecessary
