### ISSUE TITLE
Problem with starting game

### ISSUE THREAD

**Issue by wiors** [LDAsuku/soggy#8]
When I try to login and after pressing Tap to start, when the progress bar appears, an error occurs with the following text: uid:1-time:1671190832494[0,0,0]FormatException: Unknown char: .

System.Double.Parse (System.String s, NumberStyles style, IFormatProvider provider)
System.Single.Parse (System.String s)
HDLLGIPMLGN.GKPDJLLGANN ()
PFKPNDHICHN+OKOIKIGBPMA.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

While try to press Confirm button, nothing changes, but if try to press Esc, error changes to this:

uid:1-time:1671191611842[0,0,0]NullReferenceException: A null value was found where an object instance was required.

PFKPNDHICHN.KCLGENFOMGI ()
MoleMole.GameManager.Update ()

Further clicks on Esc do not change anything.

**Comment by njdawlk0293** [comment]
Solution here https://github.com/LDAsuku/soggy/issues/5

**Comment by wiors** [comment]
Thank you very much, it solved my problem
